create type public.weather_provider as enum ('wunderground', 'openweathermap', 'mock');

create table public.telemetry_weather_fetch (
  id bigint generated by default as identity primary key,
  received_at timestamp with time zone not null default now(),
  user_id_hash text not null,
  provider public.weather_provider not null,
  success boolean not null,
  error_stage text,
  error_code text,
  country_code text,
  settings_json jsonb not null default '{}'::jsonb,
  app_version text not null,
  build_profile text not null,
  watch_platform text,
  watch_model text,
  check ((success = true and error_stage is null and error_code is null) or (success = false and error_stage is not null and error_code is not null))
);

alter table public.telemetry_weather_fetch enable row level security;

create policy no_api_access_telemetry_weather_fetch
on public.telemetry_weather_fetch
for all
to anon, authenticated
using (false)
with check (false);

create index telemetry_weather_fetch_user_hour_idx
  on public.telemetry_weather_fetch (user_id_hash, received_at);

create index telemetry_weather_fetch_dau_idx
  on public.telemetry_weather_fetch ((((received_at at time zone 'UTC'::text))::date), user_id_hash);
