create type public.weather_provider as enum ('wunderground', 'openweathermap', 'mock');

create table public.telemetry_weather_fetch (
  id bigint generated by default as identity primary key,
  received_at timestamp with time zone not null default now(),
  account_token_hash text not null,
  watch_token_hash text,
  provider public.weather_provider not null,
  success boolean not null,
  error text,
  country_code text,
  settings_json jsonb not null default '{}'::jsonb,
  app_version text not null,
  build_profile text not null,

  -- https://developer.repebble.com/docs/pebblekit-js/Pebble/#WatchInfo
  watch_platform text,
  watch_model text,
  
  check ((success = true and error is null) or (success = false and error is not null and length(btrim(error)) > 0))
);

alter table public.telemetry_weather_fetch enable row level security;

create policy no_api_access_telemetry_weather_fetch
on public.telemetry_weather_fetch
for all
to anon, authenticated
using (false)
with check (false);

create index telemetry_weather_fetch_account_hour_idx
  on public.telemetry_weather_fetch (account_token_hash, received_at);

create index telemetry_weather_fetch_dau_idx
  on public.telemetry_weather_fetch ((((received_at at time zone 'UTC'::text))::date), account_token_hash);
