create type "public"."weather_provider" as enum ('wunderground', 'openweathermap', 'mock');


  create table "public"."telemetry_weather_fetch" (
    "id" bigint generated by default as identity not null,
    "received_at" timestamp with time zone not null default now(),
    "account_token_hash" text not null,
    "watch_token_hash" text,
    "provider" public.weather_provider not null,
    "success" boolean not null,
    "error_stage" text,
    "error_code" text,
    "country_code" text,
    "settings_json" jsonb not null default '{}'::jsonb,
    "app_version" text not null,
    "build_profile" text not null,
    "watch_platform" text,
    "watch_model" text
      );


alter table "public"."telemetry_weather_fetch" enable row level security;

CREATE INDEX telemetry_weather_fetch_account_hour_idx ON public.telemetry_weather_fetch USING btree (account_token_hash, received_at);

CREATE INDEX telemetry_weather_fetch_dau_idx ON public.telemetry_weather_fetch USING btree ((((received_at AT TIME ZONE 'UTC'::text))::date), account_token_hash);

CREATE UNIQUE INDEX telemetry_weather_fetch_pkey ON public.telemetry_weather_fetch USING btree (id);

alter table "public"."telemetry_weather_fetch" add constraint "telemetry_weather_fetch_pkey" PRIMARY KEY using index "telemetry_weather_fetch_pkey";

alter table "public"."telemetry_weather_fetch" add constraint "telemetry_weather_fetch_check" CHECK ((((success = true) AND (error_stage IS NULL) AND (error_code IS NULL)) OR ((success = false) AND (error_stage IS NOT NULL) AND (error_code IS NOT NULL)))) not valid;

alter table "public"."telemetry_weather_fetch" validate constraint "telemetry_weather_fetch_check";

grant delete on table "public"."telemetry_weather_fetch" to "anon";

grant insert on table "public"."telemetry_weather_fetch" to "anon";

grant references on table "public"."telemetry_weather_fetch" to "anon";

grant select on table "public"."telemetry_weather_fetch" to "anon";

grant trigger on table "public"."telemetry_weather_fetch" to "anon";

grant truncate on table "public"."telemetry_weather_fetch" to "anon";

grant update on table "public"."telemetry_weather_fetch" to "anon";

grant delete on table "public"."telemetry_weather_fetch" to "authenticated";

grant insert on table "public"."telemetry_weather_fetch" to "authenticated";

grant references on table "public"."telemetry_weather_fetch" to "authenticated";

grant select on table "public"."telemetry_weather_fetch" to "authenticated";

grant trigger on table "public"."telemetry_weather_fetch" to "authenticated";

grant truncate on table "public"."telemetry_weather_fetch" to "authenticated";

grant update on table "public"."telemetry_weather_fetch" to "authenticated";

grant delete on table "public"."telemetry_weather_fetch" to "service_role";

grant insert on table "public"."telemetry_weather_fetch" to "service_role";

grant references on table "public"."telemetry_weather_fetch" to "service_role";

grant select on table "public"."telemetry_weather_fetch" to "service_role";

grant trigger on table "public"."telemetry_weather_fetch" to "service_role";

grant truncate on table "public"."telemetry_weather_fetch" to "service_role";

grant update on table "public"."telemetry_weather_fetch" to "service_role";


  create policy "no_api_access_telemetry_weather_fetch"
  on "public"."telemetry_weather_fetch"
  as permissive
  for all
  to anon, authenticated
using (false)
with check (false);



